import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/main/Footer";
import { ThemeProvider } from "next-themes";
import { NavbarDemo } from "@/components/main/NavbarDemo";
import LenisProvider from "@/components/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeAstera | Web Development Services ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} bg-[hsla(222.2,_84%,_4.9%,_1)] font-geistSans`}>
        
            <NavbarDemo />

            <ThemeProvider attribute="class" defaultTheme="dark">
               <LenisProvider>{children}</LenisProvider>
            </ThemeProvider>
            <Footer />
       
      </body>
    </html>
  );
}
